const YKS_TOPICS = {
    tyt: {
        Türkçe: ["Sözcükte Anlam", "Cümlede Anlam", "Paragrafta Anlam", "Ses Bilgisi", "Yazım Kuralları", "Noktalama İşaretleri", "Sözcük Türleri (İsim, Sıfat, Zamir, Zarf)", "Tamlamalar", "Fiiller ve Fiilimsiler", "Ekler ve Sözcükte Yapı", "Cümlenin Ögeleri", "Cümle Türleri", "Anlatım Bozuklukları"],
        Matematik: ["Temel Kavramlar: Sayı Kümeleri", "Temel Kavramlar: En Büyük ve En Küçük Değer Bulma", "Temel Kavramlar: Tek ve Çift Sayılar", "Temel Kavramlar: Pozitif ve Negatif Sayılar", "Temel Kavramlar: Asal Sayılar ve Aralarında Asal Sayılar", "Temel Kavramlar: Ardışık Sayılar", "Temel Kavramlar: Faktöriyel", "Sayı Basamakları", "Bölme ve Bölünebilme", "EBOB - EKOK", "Rasyonel Sayılar", "Basit Eşitsizlikler", "Mutlak Değer", "Üslü Sayılar", "Köklü Sayılar", "Çarpanlara Ayırma", "Oran - Orantı", "Denklem Çözme", "Sayı ve Kesir Problemleri", "Yaş Problemleri", "Yüzde Problemleri", "Kar ve Zarar Problemleri", "Karışım Problemleri", "Hız Problemleri", "İşçi Problemleri", "Grafik Problemleri", "Sayısal Yetenek Problemleri", "Mantık", "Kümeler", "Fonksiyonlar", "Polinomlar", "İkinci Dereceden Denklemler", "Permütasyon, Kombinasyon, Binom, Olasılık", "Veri, İstatistik"],
        Geometri: ["Doğruda ve Üçgende Açılar", "Üçgende Açı-Kenar Bağıntıları", "Dik Üçgen ve Özel Üçgen", "Üçgende Yardımcı Elemanlar", "İkizkenar Üçgen", "Eşkenar Üçgen", "Açıortay", "Kenarortay", "Eşlik ve Benzerlik", "Üçgende Alan", "Genel Dörtgenler", "Yamuk", "Paralelkenar", "Eşkenar Dörtgen", "Deltoid", "Dikdörtgen", "Kare", "Çokgenler", "Katı Cisimler (10. Sınıf)"],
        Fizik: ["Fizik Bilimine Giriş", "Madde ve Özellikleri", "Hareket ve Kuvvet", "İş, Güç ve Enerji", "Isı, Sıcaklık ve Genleşme", "Basınç", "Kaldırma Kuvveti", "Elektrostatik", "Elektrik ve Manyetizma", "Optik", "Dalgalar"],
        Kimya: ["Kimya Bilimi", "Atom ve Periyodik Sistem", "Kimyasal Türler Arası Etkileşimler", "Maddenin Hâlleri", "Doğa ve Kimya", "Kimyanın Temel Kanunları", "Kimyasal Hesaplamalar", "Karışımlar", "Asitler, Bazlar ve Tuzlar", "Kimya Her Yerde"],
        Biyoloji: ["Yaşam Bilimi Biyoloji", "Hücre ve Organelleri", "Canlıların Dünyası (Sınıflandırma)", "Hücre Bölünmeleri", "Üreme Çeşitleri", "Kalıtım", "Ekosistem Ekolojisi", "Güncel Çevre Sorunları"],
        Tarih: ["Tarih ve Zaman", "İnsanlığın İlk Dönemleri", "Orta Çağ'da Dünya", "İlk ve Orta Çağlarda Türk Dünyası", "İslam Medeniyetinin Doğuşu", "Türklerin İslamiyet'i Kabulü", "Yerleşme ve Devletleşme Sürecinde Selçuklu", "Beylikten Devlete Osmanlı", "Dünya Gücü Osmanlı", "Osmanlı Merkez Teşkilatı", "Klasik Çağda Osmanlı", "Değişen Dünya Dengeleri", "Milli Mücadele", "Atatürkçülük ve İnkılaplar"],
        Coğrafya: ["Doğa ve İnsan", "Dünya'nın Şekli ve Hareketleri", "Coğrafi Konum", "Harita Bilgisi", "İklim Bilgisi", "Dünya'nın Tektonik Oluşumu", "Su, Toprak ve Bitki Varlığı", "Nüfus, Yerleşme ve Göç", "Ekonomik Faaliyetler", "Bölgeler ve Ülkeler", "Doğal Afetler"],
        FelsefeDin: ["Felsefeyi Tanıma", "Felsefeyle Düşünme", "Varlık ve Bilgi Felsefesi", "Bilim, Ahlak, Din Felsefesi", "Siyaset ve Sanat Felsefesi", "Din ve İslam", "İslam ve İbadet", "Gençlik ve Değerler", "Hz. Muhammed ve Vahiy"]
    },
    aytSayisal: {
        Matematik: ["Fonksiyonlarda Uygulamalar", "İkinci Dereceden Denklemler", "Eşitsizlikler", "Parabol", "Logaritma", "Diziler", "Trigonometri", "Limit ve Süreklilik", "Türev", "İntegral"],
        Geometri: ["Doğrunun Analitik İncelenmesi", "Dönüşüm Geometrisi", "Çemberin Analitik İncelenmesi", "Katı Cisimler (İleri Seviye)"],
        Fizik: ["Vektörler", "Bağıl Hareket", "Newton'un Hareket Yasaları", "Atışlar", "İki Boyutta Hareket", "Enerji ve Hareket", "İtme ve Çizgisel Momentum", "Tork, Denge ve Ağırlık Merkezi", "Basit Makineler", "Elektriksel Kuvvet, Potansiyel", "Manyetizma ve Elektromanyetik İndüklenme", "Alternatif Akım", "Çembersel Hareket", "Basit Harmonik Hareket", "Dalga Mekaniği", "Modern Fizik"],
        Kimya: ["Modern Atom Teorisi", "Gazlar", "Sıvı Çözeltiler ve Çözünürlük", "Kimyasal Tepkimelerde Enerji", "Kimyasal Tepkimelerde Hız", "Kimyasal Tepkimelerde Denge", "Asit-Baz Dengesi", "Çözünürlük Dengesi", "Elektrokimya", "Karbon Kimyasına Giriş", "Organik Bileşikler"],
        Biyoloji: ["Sinir Sistemi", "Endokrin Sistem ve Duyu Organları", "Destek ve Hareket Sistemi", "Sindirim Sistemi", "Dolaşım ve Bağışıklık Sistemi", "Solunum Sistemi", "Üriner Sistem", "Üreme Sistemi", "Komünite ve Popülasyon Ekolojisi", "Genden Proteine", "Canlılık ve Enerji", "Fotosentez ve Kemosentez", "Hücresel Solunum", "Bitki Biyolojisi"]
    },
    aytEa: {
        Matematik: ["Fonksiyonlarda Uygulamalar", "İkinci Dereceden Denklemler", "Eşitsizlikler", "Parabol", "Logaritma", "Diziler", "Trigonometri", "Limit ve Süreklilik", "Türev", "İntegral"],
        Geometri: ["Doğrunun Analitik İncelenmesi", "Dönüşüm Geometrisi", "Çemberin Analitik İncelenmesi", "Katı Cisimler (İleri Seviye)"],
        Edebiyat: ["Anlam Bilgisi (Sözcük, Cümle, Paragraf)", "Şiir Bilgisi (Aruz, Hece, Uyak)", "Söz Sanatları", "İslamiyet Öncesi ve Geçiş Dönemi", "Halk Edebiyatı", "Divan Edebiyatı", "Edebi Akımlar", "Tanzimat Edebiyatı", "Servet-i Fünun ve Fecr-i Ati", "Milli Edebiyat", "Cumhuriyet Dönemi Roman ve Şiir", "Cumhuriyet Dönemi Tiyatro"],
        Tarih1: ["TYT Tarih Konuları Detaylı", "İki Savaş Arasındaki Dönem", "II. Dünya Savaşı", "Soğuk Savaş Dönemi", "Yumuşama ve Sonrası", "Küreselleşen Dünya"],
        Coğrafya1: ["Biyoçeşitlilik ve Madde Döngüleri", "Nüfus Politikaları", "Türkiye'de Tarım, Hayvancılık, Madenler", "Türkiye'de Sanayi ve Turizm", "Kültür Bölgeleri ve Türk Kültürü", "Küresel Ticaret", "Çevre Sorunları", "Uluslararası Örgütler"]
    },
    aytSozel: {
        Edebiyat: ["Anlam Bilgisi (Sözcük, Cümle, Paragraf)", "Şiir Bilgisi (Aruz, Hece, Uyak)", "Söz Sanatları", "İslamiyet Öncesi ve Geçiş Dönemi", "Halk Edebiyatı", "Divan Edebiyatı", "Edebi Akımlar", "Tanzimat Edebiyatı", "Servet-i Fünun ve Fecr-i Ati", "Milli Edebiyat", "Cumhuriyet Dönemi Roman ve Şiir", "Cumhuriyet Dönemi Tiyatro"],
        Tarih1: ["TYT Tarih Konuları Detaylı", "İki Savaş Arasındaki Dönem", "II. Dünya Savaşı", "Soğuk Savaş Dönemi", "Yumuşama ve Sonrası", "Küreselleşen Dünya"],
        Coğrafya1: ["Biyoçeşitlilik ve Madde Döngüleri", "Nüfus Politikaları", "Türkiye'de Tarım, Hayvancılık, Madenler", "Türkiye'de Sanayi ve Turizm", "Kültür Bölgeleri ve Türk Kültürü", "Küresel Ticaret", "Çevre Sorunları", "Uluslararası Örgütler"],
        Tarih2: ["Tarih Bilimi ve İnsanlığın İlk Dönemleri", "İlk ve Orta Çağlarda Türk Dünyası", "İslam Medeniyetinin Doğuşu", "İlk Türk İslam Devletleri", "Osmanlı Devleti Kuruluş ve Yükselme", "Osmanlı Devleti Duraklama ve Gerileme", "Osmanlı Devleti Dağılma Dönemi", "İnkılap Tarihi ve Milli Mücadele Hazırlık", "Kurtuluş Savaşı Cepheler", "Atatürk İlke ve İnkılapları", "İki Savaş Arası Dönemde Türkiye ve Dünya", "II. Dünya Savaşı", "Soğuk Savaş ve Yumuşama Dönemi", "Küreselleşen Dünya"],
        Coğrafya2: ["Doğa ve İnsan Etkileşimi (Detaylı)", "Dünyanın Şekli ve Hareketleri (Detaylı)", "İklim Tipleri ve Etkileri", "İç ve Dış Kuvvetler", "Nüfus ve Göç Politikaları", "Ekonomik Faaliyetler ve Doğal Kaynaklar", "Türkiye'nin Jeopolitik Konumu", "Türkiye'de Tarım ve Hayvancılık", "Türkiye'de Madenler ve Sanayi", "Kültür Bölgeleri ve Küresel Ticaret", "Çevre Sorunları ve Doğa Koruma", "Uluslararası Örgütler"],
        FelsefeGrubu: ["Psikoloji Bilimini Tanıyalım", "Psikolojinin Temel Süreçleri", "Öğrenme, Bellek, Düşünme", "Ruh Sağlığı", "Sosyolojiye Giriş", "Toplumsal Yapı ve Değişme", "Mantığa Giriş", "Klasik ve Sembolik Mantık"]
    },
    ydt: {
        Ingilizce: ["Tenses (Zamanlar)", "Modals (Kipler)", "Active-Passive & Causatives", "Conjunctions (Bağlaçlar)", "Relative Clauses", "Noun Clauses", "Gerunds & Infinitives", "Adjectives & Adverbs", "If Clauses & Wish Clauses", "Vocabulary (Kelime Bilgisi)", "Reading Comprehension", "Translation", "Dialogue Completion", "Restatement", "Paragraph Completion"]
    }
};
